version: "3.8"

services:
  deno_app:
    image: denoland/deno:latest
    container_name: deno_app
    working_dir: /app
    volumes:
      - .:/src
    command: run --allow-all main.ts
    depends_on:
      - postgres
    ports:
      - "8000:8000"

  postgres:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
